### ISSUE TITLE
software buttons obscure app

### ISSUE THREAD

**Issue by pcvonz** [Marlinski/Rumble#5] opened 2015-12-14 03:16 UTC
Hey, the software buttons on my m8 are drawn on top of your app.

**Comment by Marlinski** [comment] 2015-12-14 04:32
Do you use android lollipop by any chance ? also if you could provide a screenshot that would be great  :-)

**Comment by TheLastProject** [comment] 2015-12-14 12:44
I see this issue on Android 5.1.1 too. Screenshot:
![tmp_7518-screenshot_2015-12-14-13-42-27-1593462883](https://cloud.githubusercontent.com/assets/1885159/11781246/bf9e9010-a268-11e5-97e5-ef6b5b7618af.png)

**Comment by PrasannaVenkadesh** [comment] 2015-12-15 14:57
@Marlinski Remember? I commented about some UI related bugs, this is it. I am not sure if this is the problem with different android versions (or) different screen sizes. I am running Android 4.1.2 and the screensize is 4" and I don't see this bug in my phone.

I have seen this bug on devices with screensize more than 4" and also interestingly those devices were also running Android 5, that is why I am not able confirm if it is the problem due to screensize or Android version.

**Comment by taranarmo** [comment] 2015-12-15 16:08
![screenshot_20151215-190433](https://cloud.githubusercontent.com/assets/11619234/11815910/0657ea96-a35f-11e5-83d4-279a9bd67b2a.png)
Android 6.0.1, Nexus 7 2nd generation.

**Comment by PrasannaVenkadesh** [comment] 2015-12-15 16:25
Ok, just now confirmed with another device. Issue is not due to screen size but because of Android versions 5 and above.

**Comment by Marlinski** [comment] 2015-12-16 05:44
I'll check this out thanks for the feedback.

**Comment by viric** [comment] 2015-12-30 08:42
As additional info, it does not only happens for the bottom soft buttons, but also for the top android indication bar (tested in android 6).

**Comment by PrasannaVenkadesh** [comment] 2016-01-02 19:08
@Marlinski any progress on this? I think we need to give this bug high priority as we encounter a handful of people encountering this bug and this leaves the app unusable at times. I am ready to fix it, if you have identified where the bug is.

I think [Immersive Full Screen Mode](https://developer.android.com/training/system-ui/immersive.html) should fix this.

**Comment by xoir** [comment] 2016-01-05 13:38
This screenshot might show a connected problem. In this case it is the taskbar that is overlaying the app screen making it hard/impossible to add a group. I think it is the issue @viric mentioned a few days ago.

![screenshot_2015-12-29-23-12-36](https://cloud.githubusercontent.com/assets/14925165/12116392/d4311568-b3b9-11e5-907e-17937ec555e0.png)

**Comment by Dbof** [comment] 2016-01-21 17:19
I am having this problem, too. Fixed it like this: https://github.com/Marlinski/Rumble/pull/37, but only works for the groups list. I have not figured out yet how to solve it for the home activity.

Can someone confirm this does not break the GUI on older devices?

**Comment by Dbof** [comment] 2016-01-23 12:53
Just noticed the same problem on the login screen, when selecting text. The toolbar is overlapped by the statusbar.

**Comment by Dbof** [comment] 2016-01-23 13:48
Found the problem: Seems to be an incompatibility between Material Design and SlidingMenu library. See this issue for more: https://github.com/jfeinstein10/SlidingMenu/issues/680
This solution by @Den-Rimus fixes the problem:

> The best idea is to fix this in SlidingMenu's code.
> 
> In file
> YOUR-PROJECT-UNDER-GRADLE/sliding-menu/src/com/jeremyfeinstein/slidingmenu/lib/SlidingMenu.java,
> protected boolean fitSystemWindows(Rect insets) method replace
> 
> ```
>     int bottomPadding = insets.bottom;
> ```
> 
> with next:
> 
> ```
>     int bottomPadding = insets.bottom;
>     if (Build.VERSION.SDK_INT >= 21) {
>         Resources resources = getContent().getResources();
>         int resourceId = resources.getIdentifier("navigation_bar_height", "dimen", "android");
>         if (resourceId > 0) {
>             bottomPadding += resources.getDimensionPixelSize(resourceId);
>         }
>     }
> ```

**Comment by SimJoSt** [comment] 2016-08-19 13:02
Is there any noticeable progress on this?
It's the number on issue with recommending the app to other people. It just looks broken...

**Comment by Dbof** [comment] 2016-08-19 14:03
Unfortunately, @Marlinski seems to have abandoned this project. If you want to take over, I already provided a solution to the problem in my last comment. You just need to build (and distribute) the app yourself...

**Comment by Marlinski** [comment] 2016-08-19 15:07
I did not abandon the project, I wish I have more time! I will try to pick up with the issues :)

**Comment by SimJoSt** [comment] 2016-08-19 16:30
Testing wise I can support you anytime. Coding wise, maybe in 2 years ;-)

**Comment by SimJoSt** [comment] 2016-08-21 09:03
I have no idea, why there was no pullrequest made, by there was a proposed solution for this problem https://github.com/Marlinski/Rumble/issues/5#issuecomment-174187774

**Comment by Dbof** [comment] 2016-08-21 09:11
@SimJoSt Because the problem is in the [SlidingMenu](https://github.com/jfeinstein10/SlidingMenu/) library and is does not seem to be regularly updated. You need to fork it yourself and change the code.

**Comment by Marlinski** [comment] 2016-08-21 15:07
So I should fork the project and fix it myself, maybe it would be best if it was fixed upstream since SlidingMenu is a git submodule in Rumble (thanks to you dbof).

**Comment by Marlinski** [comment] 2016-08-21 15:51
I followed @Dbof  advice, can anyone test wether this patch worked ?

**Comment by SimJoSt** [comment] 2016-08-21 22:22
@Marlinski I tried setting up Android Studio and Gradle but failed.
If you give me an APK or a manual for the setup then I will test it for you.

**Comment by Marlinski** [comment] 2016-08-22 02:34
@SimJoSt It was a pain but I finally set the git submodule right. If you just clone recursively the project and then open it with android studio it should compile without issue:

git clone --recursive -j8 git@github.com:Marlinski/Rumble.git

I don't want to provide development apk as I prefer people to stick with either f-droid or google play so that I can push update :)

**Comment by SimJoSt** [comment] 2016-08-22 02:56
@Marlinski I will try to compile it again as soon as I can, but I didn't have any problems with the submodule. Android studio didn't accept Gradle 2.2, which is required for your project. It only allows for 2.14.1 and newer...

**Comment by Marlinski** [comment] 2016-08-22 03:31
@SimJoSt I have added gradle wrapper files that were missing. you can try now.

**Comment by SimJoSt** [comment] 2016-08-22 07:07
@Marlinski Perfect. The problem is gone.
Still, I get an error:

> Gradle 'Rumble' project refesh failed
> Error: Configuration with name 'default' not found.

**Comment by Marlinski** [comment] 2016-08-22 08:01
@SimJoSt you are talking about the UI problem which is gone ? should I close the issue ?
If you have an issue with the build please open another ticker :-)

**Comment by SimJoSt** [comment] 2016-08-22 09:04
Sorry for not being clear about hits :-)
The Gradle Version error was gone. The wrapper you added is working.
But I still have problems to import it properly into Android Studio (#45)

**Comment by Marlinski** [comment] 2016-08-23 08:37
Issue is fixed.

**Closed as completed by Marlinski** 2016-08-23 08:37 UTC

**Comment by SimJoSt** [comment] 2016-08-23 20:33
I concur. The problem is fixed.
