### ISSUE TITLE
Input field in the Chat area is too low.

### ISSUE THREAD

**Issue by vanitasvitae** [Marlinski/Rumble#9] opened 2015-12-19 10:05 UTC
Hi
In my Nexus 5, the Text input field is shifted too low. i can barely click it.

**Comment by aleksen** [comment] 2015-12-19 17:25
I think this is a duplicate of https://github.com/Marlinski/Rumble/issues/5

**Comment by deavmi** [comment] 2016-01-16 21:20
My friend is also experiencing this.

**Comment by Marlinski** [comment] 2016-08-21 17:51
duplicate of #5 which should be fixed now.

**Closed as completed by Marlinski** 2016-08-21 17:51 UTC
